// // 配置 Mock 路径
// require.config({
//     paths: {
//         mock: 'http://mockjs.com/dist/mock'
//     }
// })

// // 加载 Mock
// require(['mock'], function (Mock) {
//     // 使用 Mock
//     var data = Mock.mock({
//         'list|1-10': [{
//             'id|+1': 1
//         }]
//     })
//     // 输出结果
//     document.body.innerHTML +=
//         '<pre>' +
//         JSON.stringify(data, null, 4) +
//         '</pre>'
// })

// 引入mockjs
const Mock = require("mockjs");

Mock.mock("/api/data", (req, res) => {
  return {
    data: [
      {
        id: 396,
        agentName: "王利文",
        markCode: "469024000002",
        agentId: 290,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469024",
        xzqMc: "海南省省直辖县级行政区划临高县",
        orderCode: "2018071914327277",
        cNumber: "469024000047",
        cName: "博厚镇美所村委会六包村民小组",
        total: 230,
        payMethod: "现金",
        ctime: 1531981938000,
        undertakeTime: null,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531981938000,
        state: "登记成功",
        stateCode: "05",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "",
        producer: null,
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 535,
        organizationName: "海南省临高县公安局",
        isUrgent: 0
      },
      {
        id: 395,
        agentName: "李丹婷",
        markCode: "469028000004",
        agentId: 289,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469028",
        xzqMc: "海南省省直辖县级行政区划陵水黎族自治县",
        orderCode: "2018071912167612",
        cNumber: "469028000076",
        cName: "海南首茂技术服务有限公司",
        total: 460,
        payMethod: "现金",
        ctime: 1531973806000,
        undertakeTime: 1531973813000,
        markTime: 1531975730000,
        deliverTime: 1531975780000,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531975780000,
        state: "交付成功",
        stateCode: "08",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469034MA5T5D8E0L",
        producer: "黄茂河",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 687,
        organizationName: "海南省陵水黎族自治县公安局",
        isUrgent: 0
      },
      {
        id: 394,
        agentName: "陈伟伟",
        markCode: "469028000003",
        agentId: 288,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469028",
        xzqMc: "海南省省直辖县级行政区划陵水黎族自治县",
        orderCode: "2018071911497721",
        cNumber: "469028000075",
        cName: "海南亿拓利安石油化工有限公司",
        total: 690,
        payMethod: "现金",
        ctime: 1531972187000,
        undertakeTime: null,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531972187000,
        state: "登记成功",
        stateCode: "05",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469034MA5T59K79T",
        producer: null,
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 687,
        organizationName: "海南省陵水黎族自治县公安局",
        isUrgent: 0
      },
      {
        id: 393,
        agentName: "陈伟伟",
        markCode: "469028000003",
        agentId: 287,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469028",
        xzqMc: "海南省省直辖县级行政区划陵水黎族自治县",
        orderCode: "2018071911435463",
        cNumber: "469028000074",
        cName: "国睿新能源（海南）有限公司",
        total: 690,
        payMethod: "现金",
        ctime: 1531971805000,
        undertakeTime: null,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531971805000,
        state: "登记成功",
        stateCode: "05",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469034MA5T59944F",
        producer: null,
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 687,
        organizationName: "海南省陵水黎族自治县公安局",
        isUrgent: 0
      },
      {
        id: 392,
        agentName: "蒙杨天",
        markCode: "469021000003",
        agentId: 286,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469021",
        xzqMc: "海南省省直辖县级行政区划定安县",
        orderCode: "2018071911424111",
        cNumber: "469021000080",
        cName: "定安黄竹传民猪肉摊点",
        total: 80,
        payMethod: "现金",
        ctime: 1531971725000,
        undertakeTime: 1531981389000,
        markTime: 1531985191000,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531985191000,
        state: "完成制作",
        stateCode: "07",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "92469025MA5RL49K7H",
        producer: "陈宁",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 459,
        organizationName: "海南省定安县公安局",
        isUrgent: 0
      },
      {
        id: 391,
        agentName: "张小朗",
        markCode: "469021000002",
        agentId: 285,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469021",
        xzqMc: "海南省省直辖县级行政区划定安县",
        orderCode: "2018071911359067",
        cNumber: "469021000079",
        cName: "海南美味岛贸易有限公司",
        total: 100,
        payMethod: "现金",
        ctime: 1531971324000,
        undertakeTime: 1531971352000,
        markTime: 1531972558000,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531972558000,
        state: "完成制作",
        stateCode: "07",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469025MA5T5DJN41",
        producer: "黄石文",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 459,
        organizationName: "海南省定安县公安局",
        isUrgent: 0
      },
      {
        id: 390,
        agentName: "蒙杨天",
        markCode: "469021000003",
        agentId: 262,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469021",
        xzqMc: "海南省省直辖县级行政区划定安县",
        orderCode: "2018071911342953",
        cNumber: "469021000068",
        cName: "海南祥云港园林工程有限公司",
        total: 560,
        payMethod: "现金",
        ctime: 1531971261000,
        undertakeTime: null,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531971261000,
        state: "已取消",
        stateCode: "14",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469025MA5T5CL73J",
        producer: null,
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 459,
        organizationName: "海南省定安县公安局",
        isUrgent: 0
      },
      {
        id: 389,
        agentName: "吴吉宝",
        markCode: "469024000001",
        agentId: 284,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469024",
        xzqMc: "海南省省直辖县级行政区划临高县",
        orderCode: "2018071911269780",
        cNumber: "469024000046",
        cName: "海南健诚通信设备有限公司",
        total: 460,
        payMethod: "现金",
        ctime: 1531970797000,
        undertakeTime: 1531987629000,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531987629000,
        state: "承接成功",
        stateCode: "06",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469028MA5T5C9C84",
        producer: "符娇妹",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 535,
        organizationName: "海南省临高县公安局",
        isUrgent: 0
      },
      {
        id: 400,
        agentName: "周军义",
        markCode: "469001000001",
        agentId: 294,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469001",
        xzqMc: "海南省省直辖县级行政区划五指山市",
        orderCode: "2018071915501446",
        cNumber: "469001000038",
        cName: "五指山三义餐饮店",
        total: 510,
        payMethod: "现金",
        ctime: 1531986600000,
        undertakeTime: 1531986620000,
        markTime: 1531987899000,
        deliverTime: 1531987962000,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531987962000,
        state: "交付成功",
        stateCode: "08",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "92469001MA5T4RBN6J",
        producer: "宁尚喜",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 260,
        organizationName: "海南省五指山市公安局",
        isUrgent: 0
      },
      {
        id: 399,
        agentName: "李明亮",
        markCode: "469001000002",
        agentId: 293,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469001",
        xzqMc: "海南省省直辖县级行政区划五指山市",
        orderCode: "2018071915299474",
        cNumber: "469001000037",
        cName: "五指山肯麦基餐厅",
        total: 280,
        payMethod: "现金",
        ctime: 1531985389000,
        undertakeTime: 1531985399000,
        markTime: 1531985637000,
        deliverTime: 1531985744000,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531985744000,
        state: "交付成功",
        stateCode: "08",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "92469001MA5T49DU7J",
        producer: "赖芝仙",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 260,
        organizationName: "海南省五指山市公安局",
        isUrgent: 0
      },
      {
        id: 398,
        agentName: "张禹",
        markCode: "469028000001",
        agentId: 292,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469028",
        xzqMc: "海南省省直辖县级行政区划陵水黎族自治县",
        orderCode: "2018071915143424",
        cNumber: "469028000077",
        cName: "陵水英州八零九八户外家居馆",
        total: 230,
        payMethod: "现金",
        ctime: 1531984486000,
        undertakeTime: 1531984498000,
        markTime: 1531985697000,
        deliverTime: 1531985724000,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531985724000,
        state: "交付成功",
        stateCode: "08",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "92469034MA5T5ACY16",
        producer: "林伟坚",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 687,
        organizationName: "海南省陵水黎族自治县公安局",
        isUrgent: 0
      },
      {
        id: 397,
        agentName: "陈珮珊",
        markCode: "469001000002",
        agentId: 291,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469001",
        xzqMc: "海南省省直辖县级行政区划五指山市",
        orderCode: "2018071915141276",
        cNumber: "469001000036",
        cName: "五指山印象水满茶叶专业合作社",
        total: 280,
        payMethod: "现金",
        ctime: 1531984445000,
        undertakeTime: 1531984456000,
        markTime: 1531984639000,
        deliverTime: 1531984677000,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531984677000,
        state: "交付成功",
        stateCode: "08",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "93469001MA5RHCM73K",
        producer: "赖芝仙",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 260,
        organizationName: "海南省五指山市公安局",
        isUrgent: 0
      },
      {
        id: 396,
        agentName: "王利文",
        markCode: "469024000002",
        agentId: 290,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469024",
        xzqMc: "海南省省直辖县级行政区划临高县",
        orderCode: "2018071914327277",
        cNumber: "469024000047",
        cName: "博厚镇美所村委会六包村民小组",
        total: 230,
        payMethod: "现金",
        ctime: 1531981938000,
        undertakeTime: null,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531981938000,
        state: "登记成功",
        stateCode: "05",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "",
        producer: null,
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 535,
        organizationName: "海南省临高县公安局",
        isUrgent: 0
      },
      {
        id: 395,
        agentName: "李丹婷",
        markCode: "469028000004",
        agentId: 289,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469028",
        xzqMc: "海南省省直辖县级行政区划陵水黎族自治县",
        orderCode: "2018071912167612",
        cNumber: "469028000076",
        cName: "海南首茂技术服务有限公司",
        total: 460,
        payMethod: "现金",
        ctime: 1531973806000,
        undertakeTime: 1531973813000,
        markTime: 1531975730000,
        deliverTime: 1531975780000,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531975780000,
        state: "交付成功",
        stateCode: "08",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469034MA5T5D8E0L",
        producer: "黄茂河",
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 687,
        organizationName: "海南省陵水黎族自治县公安局",
        isUrgent: 0
      },
      {
        id: 394,
        agentName: "陈伟伟",
        markCode: "469028000003",
        agentId: 288,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469028",
        xzqMc: "海南省省直辖县级行政区划陵水黎族自治县",
        orderCode: "2018071911497721",
        cNumber: "469028000075",
        cName: "海南亿拓利安石油化工有限公司",
        total: 690,
        payMethod: "现金",
        ctime: 1531972187000,
        undertakeTime: null,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531972187000,
        state: "登记成功",
        stateCode: "05",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469034MA5T59K79T",
        producer: null,
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 687,
        organizationName: "海南省陵水黎族自治县公安局",
        isUrgent: 0
      },
      {
        id: 393,
        agentName: "陈伟伟",
        markCode: "469028000003",
        agentId: 287,
        xzqSbm: "460000",
        xzqDsbm: "469000",
        xzqQbm: "469028",
        xzqMc: "海南省省直辖县级行政区划陵水黎族自治县",
        orderCode: "2018071911435463",
        cNumber: "469028000074",
        cName: "国睿新能源（海南）有限公司",
        total: 690,
        payMethod: "现金",
        ctime: 1531971805000,
        undertakeTime: null,
        markTime: null,
        deliverTime: null,
        scrapTime: null,
        destroyTime: null,
        lossesTime: null,
        lastcheckTime: null,
        lastUpdateTime: 1531971805000,
        state: "登记成功",
        stateCode: "05",
        shippingMethod: "自提",
        courierNumber: null,
        deliveryBoy: null,
        licenceCode: "91469034MA5T59944F",
        producer: null,
        orderSource: "本地",
        invoiceId: null,
        isVoice: 0,
        isMsg: null,
        consName: null,
        consPhone: null,
        consAddress: null,
        type: 0,
        remarks: null,
        examineReason: null,
        sealUserId: null,
        payOrderNo: null,
        organizationId: 687,
        organizationName: "海南省陵水黎族自治县公安局",
        isUrgent: 0
      }
    ]
  };
});
Mock.mock("/api/data2", (req, res) => {
  return {
    data: [
        {
          upmsPermission: {
            permissionId: 27,
            systemId: null,
            pid: 0,
            name: "帮助中心",
            type: null,
            permissionValue: "",
            uri: "/help",
            icon: "#",
            status: 1,
            ctime: 1524125183000,
            orders: 11
          },
          children: [
            {
              upmsPermission: {
                permissionId: 59,
                systemId: null,
                pid: 27,
                name: "帮助中心",
                type: null,
                permissionValue: null,
                uri: "/home/help",
                icon: "#",
                status: 1,
                ctime: 1524651653000,
                orders: 0
              },
              children: [
                {
                  upmsPermission: {
                    permissionId: 139,
                    systemId: null,
                    pid: 59,
                    name: "操作手册",
                    type: null,
                    permissionValue: null,
                    uri: "/home/help/operationManual",
                    icon: "#",
                    status: 1,
                    ctime: 1528967952000,
                    orders: 2
                  },
                  children: []
                },
                {
                  upmsPermission: {
                    permissionId: 123,
                    systemId: null,
                    pid: 59,
                    name: "驱动下载",
                    type: null,
                    permissionValue: null,
                    uri: "/home/help/commonSealFlow",
                    icon: "#",
                    status: 1,
                    ctime: 1525834477000,
                    orders: 1
                  },
                  children: []
                }
              ]
            }
          ]
        },
        {
          upmsPermission: {
            permissionId: 43,
            systemId: null,
            pid: 0,
            name: "日常管理",
            type: null,
            permissionValue: null,
            uri: "/everyday",
            icon: "#",
            status: 1,
            ctime: 1524556502000,
            orders: 5
          },
          children: [
            {
              upmsPermission: {
                permissionId: 52,
                systemId: null,
                pid: 43,
                name: "日常管理",
                type: null,
                permissionValue: null,
                uri: "#",
                icon: "#",
                status: 1,
                ctime: 1524650411000,
                orders: 1
              },
              children: [
                {
                  upmsPermission: {
                    permissionId: 53,
                    systemId: null,
                    pid: 52,
                    name: "制作单位管理",
                    type: null,
                    permissionValue: null,
                    uri: "/home/everyday/productionUnit",
                    icon: "#",
                    status: 1,
                    ctime: 1524650451000,
                    orders: 0
                  },
                  children: []
                },
                {
                  upmsPermission: {
                    permissionId: 132,
                    systemId: null,
                    pid: 52,
                    name: "可疑情况管理",
                    type: null,
                    permissionValue: null,
                    uri: "/home/everyday/suspicious",
                    icon: "#",
                    status: 1,
                    ctime: 1526347890000,
                    orders: 4
                  },
                  children: []
                },
                {
                  upmsPermission: {
                    permissionId: 73,
                    systemId: null,
                    pid: 52,
                    name: "从业人员查询",
                    type: null,
                    permissionValue: null,
                    uri: "/home/everyday/employeeG",
                    icon: "#",
                    status: 1,
                    ctime: 1524702448000,
                    orders: 2
                  },
                  children: []
                }
              ]
            }
          ]
        },
        {
          upmsPermission: {
            permissionId: 23,
            systemId: null,
            pid: 0,
            name: "业务管理",
            type: null,
            permissionValue: "",
            uri: "/business",
            icon: "#",
            status: 1,
            ctime: 1524125115000,
            orders: 2
          },
          children: [
            {
              upmsPermission: {
                permissionId: 35,
                systemId: null,
                pid: 23,
                name: "印章管理",
                type: null,
                permissionValue: "",
                uri: "#",
                icon: "#",
                status: 1,
                ctime: 1524208297000,
                orders: 1
              },
              children: [
                {
                  upmsPermission: {
                    permissionId: 78,
                    systemId: null,
                    pid: 35,
                    name: "印章查询",
                    type: null,
                    permissionValue: null,
                    uri: "/home/business/sealInquiry",
                    icon: "#",
                    status: 1,
                    ctime: 1524709944000,
                    orders: 1
                  },
                  children: []
                },
                {
                  upmsPermission: {
                    permissionId: 77,
                    systemId: null,
                    pid: 35,
                    name: "订单查询",
                    type: null,
                    permissionValue: null,
                    uri: "/home/business/orderInquiry",
                    icon: "#",
                    status: 1,
                    ctime: 1524709917000,
                    orders: 0
                  },
                  children: []
                }
              ]
            },
            {
              upmsPermission: {
                permissionId: 76,
                systemId: null,
                pid: 23,
                name: "私章管理",
                type: null,
                permissionValue: null,
                uri: "#",
                icon: "#",
                status: 1,
                ctime: 1524709790000,
                orders: 2
              },
              children: [
                {
                  upmsPermission: {
                    permissionId: 83,
                    systemId: null,
                    pid: 76,
                    name: "订单查询",
                    type: null,
                    permissionValue: null,
                    uri: "/home/business/orderInquirys",
                    icon: "#",
                    status: 1,
                    ctime: 1525395627000,
                    orders: 1
                  },
                  children: []
                }
              ]
            }
          ]
        },
        {
          upmsPermission: {
            permissionId: 44,
            systemId: null,
            pid: 0,
            name: "首页",
            type: null,
            permissionValue: null,
            uri: "",
            icon: "#",
            status: 1,
            ctime: 1524558041000,
            orders: 0
          },
          children: []
        },
        {
          upmsPermission: {
            permissionId: 26,
            systemId: null,
            pid: 0,
            name: "统计分析",
            type: null,
            permissionValue: "",
            uri: "/count",
            icon: "#",
            status: 1,
            ctime: 1524125169000,
            orders: 10
          },
          children: [
            {
              upmsPermission: {
                permissionId: 106,
                systemId: null,
                pid: 26,
                name: "查询统计",
                type: null,
                permissionValue: null,
                uri: "#",
                icon: "#",
                status: 1,
                ctime: 1525751410000,
                orders: 1
              },
              children: [
                {
                  upmsPermission: {
                    permissionId: 119,
                    systemId: null,
                    pid: 106,
                    name: "用户统计",
                    type: null,
                    permissionValue: null,
                    uri: "/home/count/usertj",
                    icon: "#",
                    status: 1,
                    ctime: 1525765238000,
                    orders: 5
                  },
                  children: []
                },
                {
                  upmsPermission: {
                    permissionId: 118,
                    systemId: null,
                    pid: 106,
                    name: "印章统计",
                    type: null,
                    permissionValue: null,
                    uri: "/home/count/sealtj",
                    icon: "#",
                    status: 1,
                    ctime: 1525765205000,
                    orders: 4
                  },
                  children: []
                },
                {
                  upmsPermission: {
                    permissionId: 117,
                    systemId: null,
                    pid: 106,
                    name: "交易统计",
                    type: null,
                    permissionValue: null,
                    uri: "/home/count/dealtj",
                    icon: "#",
                    status: 1,
                    ctime: 1525765184000,
                    orders: 3
                  },
                  children: []
                }
              ]
            }
          ]
        }
      ]
  };
});
